'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {context,fields,fallback,source,CACHE}=require('./helpers/cardmarket-harness.cjs');
const {chromium}=require('../scripts/node_modules/playwright');
const redirect='https://prices.pokemontcg.io/cardmarket/pop5-3';
const card={name:'Mew δ',number:'3',set:'POP SERIES 5',set_name:'POP Series 5',language:'EN',source_id:'pop5-3',source_set_id:'pop5',condition:'EX',edition:'AUTO'};
const primary={id:card.source_id,name:card.name,number:card.number,set:{id:'pop5',name:'POP Series 5'},cardmarket:{url:redirect}};
// A synthetic ID only in mocked API responses; no product mapping is added to production.
const product=123456,productUrl='https://www.cardmarket.com/en/Pokemon/Products?idProduct='+product;
const secondary={id:card.source_id,name:card.name,localId:card.number,set:{id:'pop5',name:'POP Series 5'},pricing:{cardmarket:{idProduct:product}}};
function setup(options={}){const result=context(options);result.c.CONDITION_IDS=Function('return '+source.match(/const CONDITION_IDS = (.*);/)[1])();return result;}
function classify(c){const text=fs.readFileSync('cardmarket-ui-v156.js','utf8');return Function('validCardmarketRoute','validCardmarketSearch',text.slice(text.indexOf('  function classify('),text.indexOf('  const api='))+';return classify;')(c.validCardmarketRoute,c.validCardmarketSearch);}
function apiResponses(data=secondary){return async url=>({ok:true,json:async()=>url.includes('api.pokemontcg.io')?{data:primary}:data});}
test('prices redirect is never a final product route, even for the exact source ID',()=>{const {c}=setup();assert.equal(c.validCardmarketRoute(redirect,'pop5-3'),false);assert.equal(c.validCardmarketSearch(redirect),false);});
test('UI rejects external hosts, unsafe authorities, invalid products and non-search paths',()=>{
 const {c}=setup(),ui=classify(c);for(const url of [redirect,'https://api.pokemontcg.io/v2/cards/pop5-3','https://api.tcgdex.net/v2/en/cards/pop5-3','http://www.cardmarket.com/en/Pokemon/Products?idProduct=1','https://cardmarket.com/en/Pokemon/Products?idProduct=1','https://www.cardmarket.com.evil.test/en/Pokemon/Products?idProduct=1','https://user:pass@www.cardmarket.com/en/Pokemon/Products?idProduct=1','https://www.cardmarket.com:443/en/Pokemon/Products?idProduct=1',productUrl+'#x',productUrl.replace('123456','-1'),productUrl.replace('123456','1.5'),'https://www.cardmarket.com/en/Pokemon/Products/Search','https://www.cardmarket.com/anything']){assert.equal(ui(url),'UNAVAILABLE',url);assert.equal(c.validCardmarketRoute(url,'pop5-3'),false,url);}
});
test('UI: real Cardmarket Search is SEARCH and pending/idle remain unchanged',()=>{const {c}=setup(),ui=classify(c);assert.equal(ui(fallback(c,card).url),'SEARCH');assert.equal(ui(redirect,'pending'),'PENDING');assert.equal(ui(productUrl,'idle'),'UNAVAILABLE');});
test('UI: validated Singles and integer product IDs are EXACT',()=>{const {c}=setup(),ui=classify(c);for(const url of [productUrl,'https://www.cardmarket.com/en/Pokemon/Products/Singles/POP-Series-5/Mew'])assert.equal(ui(url),'EXACT');});
test('primary redirect is not published or cached; secondary ID is used with edition filters',async()=>{
 const {c,calls,storage,events}=setup({fetch:apiResponses()});const selected={...card,edition:'1ST'};fields(c,selected);c.selectCardmarketCard(selected);await c.makeLink(false);
 assert.equal(calls.length,2);assert.ok(calls[1][0].endsWith('/en/cards/pop5-3'));assert.equal(new URL(c.openBtn.href).hostname,'www.cardmarket.com');assert.equal(new URL(c.openBtn.href).searchParams.get('idProduct'),String(product));assert.equal(new URL(c.openBtn.href).searchParams.get('isFirstEd'),'Y');assert.ok(events.filter(e=>e.type==='cardscout:cm-route-ready').every(e=>new URL(e.detail.cardmarketUrl).hostname==='www.cardmarket.com'));assert.equal(JSON.parse(storage.get(CACHE))[0].url,productUrl);
});
test('missing secondary ID keeps truthful SEARCH with Mew / 3 / POP Series 5',async()=>{const {c,storage}=setup({fetch:apiResponses({...secondary,pricing:{}})});const r=await c.resolveFinalCardmarketRoute(card),u=new URL(r.url);assert.equal(r.exact,false);assert.equal(u.hostname,'www.cardmarket.com');assert.equal(u.pathname,'/en/Pokemon/Products/Search');assert.equal(u.searchParams.get('searchString'),'Mew 3 POP Series 5');assert.equal(storage.has(CACHE),false);});
for(const [condition,value] of [['NM','2'],['EX','3'],['GD','4'],['PL','6']])test('POP5 '+condition+' final host and condition for both secondary outcomes',async()=>{for(const data of [secondary,{...secondary,pricing:{}}]){const {c}=setup({fetch:apiResponses(data)}),r=await c.resolveFinalCardmarketRoute({...card,condition}),u=new URL(r.url);assert.equal(u.hostname,'www.cardmarket.com');assert.equal(u.searchParams.get('minCondition'),value);}});
test('stale redirect is purged, valid cache survives, key and unrelated storage stay unchanged',()=>{
 const good={source_id:'dp6-1',url:'https://www.cardmarket.com/en/Pokemon/Products?idProduct=278150',timestamp:Date.now()},bad={source_id:'pop5-3',url:redirect,timestamp:Date.now()};const {c,storage}=setup({storage:[[CACHE,JSON.stringify([bad,good])],['cardscout_collection_v133','[]']]});const result=c.readCardmarketRouteCache();assert.equal(result.length,1);assert.equal(result[0].url,good.url);assert.deepEqual(JSON.parse(storage.get(CACHE)),[good]);assert.equal(storage.get('cardscout_collection_v133'),'[]');assert.equal(CACHE,'cardscout_cm_route_cache_v146');
});
test('valid Cardmarket cache bypasses both APIs',async()=>{const {c,calls}=setup({storage:[[CACHE,JSON.stringify([{source_id:'pop5-3',url:productUrl,timestamp:Date.now()}])]]});assert.equal((await c.resolveFinalCardmarketRoute(card)).exact,true);assert.equal(calls.length,0);});
test('storage write denial retains valid readable cache; full denial safely resolves',async()=>{
 const {c}=setup({storage:[[CACHE,JSON.stringify([{source_id:'pop5-3',url:redirect,timestamp:Date.now()},{source_id:'dp6-1',url:productUrl,timestamp:Date.now()}])]],fetch:apiResponses()});c.localStorage.setItem=()=>{throw Error('denied');};assert.equal(c.readCardmarketRouteCache().length,1);c.localStorage.getItem=()=>{throw Error('denied');};assert.equal(new URL((await c.resolveFinalCardmarketRoute(card)).url).hostname,'www.cardmarket.com');
});
test('cache writer never stores external URLs or malformed source IDs',()=>{const {c,storage}=setup();c.cacheCardmarketRoute('pop5-3',redirect);c.cacheCardmarketRoute('../bad',productUrl);assert.equal(storage.has(CACHE),false);});
test('secondary wrong identity and invalid IDs still fail closed',async()=>{
 for(const change of [{id:'pop5-4'},{name:'Pikachu'},{localId:'4'},{set:{id:'pop9',name:'POP Series 5'}},{set:{id:'pop5',name:'POP Series 9'}},...[0,-1,1.5,'123456',Number.MAX_SAFE_INTEGER].map(idProduct=>({pricing:{cardmarket:{idProduct}}}))]){const {c}=setup({fetch:apiResponses({...secondary,...change})});const r=await c.resolveFinalCardmarketRoute(card);assert.equal(r.exact,false,JSON.stringify(change));assert.equal(new URL(r.url).pathname,'/en/Pokemon/Products/Search');}
});
test('source delta names stay intact and existing routing cleaning is unchanged',()=>{const {c}=setup();for(const [input,clean]of [['Mew δ','Mew'],['Azumarill Δ','Azumarill'],['Charizard Delta Species','Charizard'],['Bagon Delta Species','Bagon']])assert.equal(c.cleanCardmarketName(input,''),clean);fields(c,card);c.buildUrl();assert.equal(c.nameInput.value,'Mew δ');});
test('saved external links become contextual searches without changing card identity',()=>{const {c}=setup();const original=JSON.stringify(card);const u=new URL(c.safeCardmarketLink(redirect,card));assert.equal(u.hostname,'www.cardmarket.com');assert.equal(u.searchParams.get('searchString'),'Mew 3 POP Series 5');assert.equal(JSON.stringify(card),original);});
let browser,server,origin;
before(async()=>{server=http.createServer((req,res)=>{try{const f=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';res.setHeader('Content-Type',({js:'text/javascript',html:'text/html',json:'application/json',css:'text/css',png:'image/png',svg:'image/svg+xml'})[f.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(path.resolve(f)));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true});});
after(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
async function fixture(t,data){const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',serviceWorkers:'block'});t.after(()=>ctx.close());await ctx.addInitScript(()=>sessionStorage.setItem('rareworth_guest_session_v171_1','1'));const page=await ctx.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));t.after(()=>assert.deepEqual(errors,[]));await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin)return r.continue();requests.push(u.href);if(u.hostname==='api.pokemontcg.io')return r.fulfill({json:{data:primary}});if(u.hostname==='api.tcgdex.net'){if(u.pathname.endsWith('/cards/pop5-3'))return r.fulfill({json:data});if(u.pathname.endsWith('/sets/pop5'))return r.fulfill({json:require('./fixtures/en-sets-v174/pop5.json')});if(u.pathname.endsWith('/sets/PMCG1'))return r.fulfill({json:require('./fixtures/jp-sets-v160/PMCG1.json')});return r.fulfill({json:{cards:[]}});}return r.abort();});return {ctx,page,requests};}
for(const hasProduct of [true,false])test('Chromium POP5 redirect → '+(hasProduct?'secondary product':'safe SEARCH')+'; all conditions and zero published external hrefs',async t=>{
 const {ctx,page,requests}=await fixture(t,hasProduct?secondary:{...secondary,pricing:{}});await ctx.addInitScript(({CACHE,redirect})=>{localStorage.setItem(CACHE,JSON.stringify([{source_id:'pop5-3',url:redirect,timestamp:Date.now()}]));window.published=[];window.addEventListener('cardscout:cm-route-ready',e=>published.push(e.detail.cardmarketUrl));},{CACHE,redirect});await page.goto(origin);await page.waitForFunction(()=>!!window.CardCatalog?.byId('pop5-3','EN'));await page.locator('#quickInput').fill('Mew 3 pop 5');await page.locator('.suggestion').filter({hasText:'#3'}).first().click();
 for(const [cond,value]of [['NM','2'],['EX','3'],['GD','4'],['PL','6']]){await page.locator('.visiblePreferences [data-value="'+cond+'"]').click();await page.waitForFunction(value=>{const a=document.querySelector('#openBtn');return a.dataset.cmState==='ready'&&new URL(a.href).searchParams.get('minCondition')===value},value);const u=new URL(await page.locator('#openBtn').getAttribute('href'));assert.equal(u.hostname,'www.cardmarket.com');assert.equal(await page.locator('#openBtn').getAttribute('data-cm-route'),hasProduct?'EXACT':'SEARCH');if(hasProduct)assert.equal(u.searchParams.get('idProduct'),String(product));else assert.equal(u.searchParams.get('searchString'),'Mew 3 POP Series 5');}
 assert.ok(requests.some(u=>u.includes('api.pokemontcg.io')));assert.ok(requests.some(u=>u.endsWith('/cards/pop5-3')));assert.ok((await page.evaluate(()=>published)).every(u=>new URL(u).hostname==='www.cardmarket.com'));assert.equal(await page.evaluate(()=>selectedCardIdentity(document.querySelector('#openBtn').href).name),'Mew δ');assert.ok(!(await page.evaluate(CACHE=>localStorage.getItem(CACHE),CACHE)).includes('prices.pokemontcg.io'));
});
test('Chromium stale Recent, Favorites and Collection links are never clickable external redirects; storage is retained',async t=>{
 const {ctx,page}=await fixture(t,{...secondary,pricing:{}});const row={uid:'saved-mew',name:'Mew δ',number:'3',set:'POP SERIES 5',setName:'POP Series 5',sourceId:'pop5-3',source_set_id:'pop5',language:'EN',condition:'EX',edition:'AUTO',variant:'NORMAL',listType:'OWNED',qty:2,paidEach:4.25,cardmarketUrl:redirect};const recent={...card,id:'saved-recent',kind:'card',url:redirect,cardmarketUrl:redirect,lang:'EN',cond:'EX'};
 await ctx.addInitScript(({row,recent})=>{localStorage.setItem('cardscout_collection_v133',JSON.stringify([row]));localStorage.setItem('whatnotai_mobile_recent_v37',JSON.stringify([recent]));localStorage.setItem('whatnotai_mobile_favorites_v37',JSON.stringify([recent]));window.unsafe=[];new MutationObserver(()=>{for(const a of document.querySelectorAll('#recentList a,#favoriteList a,#collectionList a'))if(a.href.includes('prices.pokemontcg.io'))unsafe.push(a.href);}).observe(document,{subtree:true,childList:true,attributes:true,attributeFilter:['href']});},{row,recent});await page.goto(origin);await page.locator('#navRecent').click();await page.locator('#recentList .openMini').waitFor();assert.equal(new URL(await page.locator('#recentList .openMini').getAttribute('href')).hostname,'www.cardmarket.com');await page.locator('#navCollection').click();await page.locator('#collectionList .collectionCard').waitFor();await page.locator('#collectionList a').first().waitFor({state:'attached'});assert.equal(new URL(await page.locator('#collectionList a').first().getAttribute('href')).hostname,'www.cardmarket.com');assert.deepEqual(await page.evaluate(()=>unsafe),[]);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('cardscout_collection_v133'))[0]);for(const key of ['name','number','set','sourceId','source_set_id','qty','paidEach','variant','listType','condition','cardmarketUrl'])assert.equal(saved[key],row[key]);
});
test('Chromium JP Machamp native NM/EX remains exact with no language parameter',async t=>{const {page}=await fixture(t,secondary);await page.goto(origin);await page.locator('.visiblePreferences [data-value="JP"]').click();await page.waitForFunction(()=>!!window.CardCatalog?.byId('PMCG1-057','JP'));await page.locator('#quickInput').fill('Machamp');await page.locator('.suggestion').filter({hasText:'PMCG1-057'}).click();for(const [cond,n]of [['NM','2'],['EX','3']]){await page.locator('.visiblePreferences [data-value="'+cond+'"]').click();await page.waitForFunction(n=>document.querySelector('#openBtn').href==='https://www.cardmarket.com/en/Pokemon/Products/Singles/Expansion-Pack/Machamp-EXP?minCondition='+n,n);}});
test('fixture catalog cache survives second load and 13 days; expires after 14 days',async t=>{
 const {page,requests}=await fixture(t,secondary),key='cardscout_search_catalog_v152_EN_v174';await page.goto(origin);await page.waitForFunction(()=>!!window.CardCatalog?.byId('pop5-3','EN'));
 await page.evaluate(key=>{const cache=JSON.parse(localStorage.getItem(key));cache.savedAt=Date.now()-13*86400000;localStorage.setItem(key,JSON.stringify(cache));},key);requests.length=0;await page.reload();await page.waitForFunction(()=>!!window.CardCatalog?.byId('pop5-3','EN'));assert.equal(requests.filter(u=>u.includes('/en/sets/')).length,0);
 await page.evaluate(key=>{const cache=JSON.parse(localStorage.getItem(key));cache.savedAt=Date.now()-15*86400000;localStorage.setItem(key,JSON.stringify(cache));},key);requests.length=0;await page.reload();await page.waitForFunction(()=>!!window.CardCatalog?.byId('pop5-3','EN'));assert.ok(requests.some(u=>u.includes('/en/sets/pop5')));
});
test('PWA v174.1 removes v174 cache only, precaches changed scripts and retains local data',async t=>{
 const ctx=await browser.newContext();t.after(()=>ctx.close());const page=await ctx.newPage();await ctx.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.fulfill({json:{cards:[]}}));
 // Seed the actual previous cache before registering the new service worker.
 await page.goto(origin+'/manifest.json');await page.evaluate(async()=>{await caches.open('rareworth-shell-v174');await caches.open('unrelated-cache');localStorage.setItem('rareworth_device_id_v170','preserved');sessionStorage.setItem('rareworth_guest_session_v171_1','1');});await page.goto(origin);await page.evaluate(()=>navigator.serviceWorker.ready);
 await page.waitForFunction(async()=>{const names=await caches.keys();return names.includes('rareworth-shell-v174-1')&&!names.includes('rareworth-shell-v174');});
 const cache=await page.evaluate(async()=>({names:await caches.keys(),urls:(await (await caches.open('rareworth-shell-v174-1')).keys()).map(r=>r.url)}));assert.ok(cache.names.includes('unrelated-cache'));assert.ok(cache.urls.every(u=>new URL(u).origin===origin));for(const file of ['app-v137.js','cardmarket-ui-v156.js','ui-v137-collection.js','brand-v172.js'])assert.ok(cache.urls.some(u=>u.endsWith(file+'?build=174-1-cardmarket-host-hotfix')));assert.equal(await page.evaluate(()=>RareWorthBrand.version),'v174.1');assert.equal(await page.evaluate(()=>localStorage.getItem('rareworth_device_id_v170')),'preserved');
});
