'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){const calls=[],c={window:{},CM_SOURCE_SETS:{SET:['s1'],SHARED:['s2','s3']}};vm.createContext(c);vm.runInContext(fs.readFileSync('card-identity-v154.js','utf8'),c);c.window.CardArtwork={lookup:async x=>{calls.push(x);return c.data;}};return {...c,api:c.window.CardIdentity,calls,setData:x=>c.data=x};}
test('Source metadata wins; language namespaces stay separate',()=>{const c=setup();c.window.CM_PRODUCT_CATALOG={'s1-7':{id:'s1-7',name:'Exact',number:'7',set:{name:'SET'}}};const en=c.api.normalize({source_id:'s1-7',name:'Wrong',set:'AUTO',lang:'EN'});assert.equal(en.name,'Exact');assert.equal(en.number,'7');assert.equal(en.sourceId,en.source_id);assert.equal(en.catalogId,en.source_id);const jp=c.api.normalize({source_id:'s1-7',name:'Japanese',set:'AUTO',lang:'JP'});assert.equal(jp.name,'Japanese');assert.equal(jp.set,'AUTO');});
test('Name-only AUTO never becomes a card and never requests metadata',async()=>{const c=setup();const raw={name:'Same',set:'AUTO',image:'https://assets.tcgdex.net/wrong',exact:true};const x=await c.api.hydrate(raw);assert.equal(x.kind,'query');assert.equal(x.image,'');assert.equal(c.calls.length,0);assert.equal(raw.exact,true);});
test('Exact and query dedupe keys are distinct even with identical quick text and URL',()=>{const c=setup();const base={name:'Same',quick:'Same',url:'https://example.org'};assert.notEqual(c.api.key(base),c.api.key({...base,source_id:'s1-7'}));assert.notEqual(c.api.key({...base,source_id:'s1-7',variant:'NORMAL'}),c.api.key({...base,source_id:'s1-7',variant:'STAMPED'}));});
test('Unknown source ID hydrates exact metadata in memory without modifying input',async()=>{const c=setup();c.setData({id:'s1-7',name:'Exact',localId:'7',set:{id:'s1',name:'Set label'},image:'https://assets.tcgdex.net/en/s1/7'});const raw={source_id:'s1-7',set:'AUTO',name:'Old',lang:'EN'};const before=JSON.stringify(raw),x=await c.api.hydrate(raw);assert.equal(x.number,'7');assert.equal(x.set,'SET');assert.equal(x.image,c.api.normalize(raw).image);assert.equal(JSON.stringify(raw),before);});
test('Unique tuple metadata recovery validates name, number and source set',async()=>{const c=setup();const raw={name:'Exact',number:'7',set:'SET',lang:'EN'};c.setData({id:'s1-7',name:'Exact',localId:'7',set:{id:'s1'},image:'image'});assert.equal((await c.api.hydrate(raw)).source_id,'s1-7');const bad=setup();bad.setData({id:'s2-7',name:'Exact',localId:'7',set:{id:'s2'}});assert.equal((await bad.api.hydrate(raw)).kind,'query');});
test('Ambiguous shared-set tuple never picks the first candidate',async()=>{const c=setup();const x=await c.api.hydrate({name:'Same',number:'7',set:'SHARED'});assert.equal(x.kind,'query');assert.equal(c.calls.length,0);});
test('Wrong source metadata is rejected',async()=>{const c=setup();c.setData({id:'s1-8',name:'Wrong',localId:'8',set:{id:'s1'},image:'wrong'});const x=await c.api.hydrate({source_id:'s1-7',name:'Exact',set:'AUTO'});assert.equal(x.number,'');assert.equal(x.image,'');});
