'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const recent='whatnotai_mobile_recent_v37',collection='cardscout_collection_v133';
(async()=>{
 const server=http.createServer((req,res)=>{try{const f=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';res.setHeader('Content-Type',({js:'text/javascript',html:'text/html',css:'text/css',json:'application/json'})[f.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(path.resolve(f)));}catch{res.writeHead(404).end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
  const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='127.0.0.1')return r.continue();if(u.hostname==='api.tcgdex.net'){const p=u.pathname.split('/'),f=`tests/fixtures/artwork-v155/${p[2]}-${p.at(-1)}${p[3]==='sets'?'-set':''}.json`;return r.fulfill({json:fs.existsSync(f)?JSON.parse(fs.readFileSync(f)):{cards:[]}});}return r.abort();});
  await page.goto('http://127.0.0.1:'+server.address().port);
  await page.locator('.visiblePreferences [data-value="JP"]').click();
  await page.waitForFunction(()=>window.CardCatalog?.byId('neo1-061','JP'));
  // Preserve the v156 SEARCH scenario: this fixture has no marketplace counterpart.
  await page.evaluate(()=>{delete window.CM_PRODUCT_CATALOG['neo1-74'];});
  await page.locator('#quickInput').fill('Snubbull');
  await page.locator('.suggestion').filter({hasText:'Snubbull'}).first().click();
  await page.waitForFunction(()=>document.querySelector('#openBtn').dataset.cmRoute==='SEARCH');
  const selected=await page.evaluate(()=>currentCardmarketCard());assert.equal(selected.source_id,'neo1-061');assert.equal(selected.language,'JP');
  assert.equal(await page.locator('#openBtn span').textContent(),'Bekijk zoekresultaten');
  assert.equal(await page.locator('#openBtn small').textContent(),'Controleer de juiste kaart');
  assert.equal(await page.locator('#selectedCardRoute').textContent(),'Zoekresultaten op Cardmarket · controleer de juiste uitvoering');
  assert.equal(await page.locator('#resultOpenBtn span').textContent(),'Bekijk zoekresultaten');
  assert.equal(await page.locator('#resultHint').textContent(),await page.locator('#selectedCardRoute').textContent());
  assert.equal(new URL(await page.locator('#openBtn').getAttribute('href')).searchParams.get('searchString'),'Snubbull');
  assert.equal(await page.locator('#selectedCardArt img').count(),0);
  await page.locator('#selectedCardArt.artUnavailable').waitFor();
  console.log('PASS JP Snubbull SEARCH across panel/dock/detail; honest unavailable artwork');
  await page.locator('.visiblePreferences [data-value="EX"]').click();
  await page.locator('.visiblePreferences [data-value="1ST"]').click();
  await page.evaluate(()=>makeLink(false));
  const saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k))[0],recent);
  assert.equal(saved.kind,'card');assert.equal(saved.source_id,'neo1-061');assert.equal(saved.language,'JP');assert.equal(saved.condition,'EX');assert.equal(saved.edition,'1ST');
  await page.reload();await page.evaluate(()=>{delete window.CM_PRODUCT_CATALOG['neo1-74'];});await page.locator('#navRecent').click();
  await page.waitForFunction(()=>document.querySelector('#recentList .openMini')?.dataset.cmRoute==='SEARCH');
  assert.match(await page.locator('#recentList .openMini').first().getAttribute('aria-label'),/Bekijk zoekresultaten/);
  await page.locator('#recentList .useBtn').first().click();
  await page.waitForFunction(()=>document.querySelector('#openBtn').dataset.cmRoute==='SEARCH');
  const restored=await page.evaluate(()=>selectedCardIdentity(document.querySelector('#openBtn').href));
  for(const key of ['source_id','language','set','set_name','source_set_id','source_set_name','name','number','condition','edition','variant'])assert.equal(restored[key],saved[key],key);
  console.log('PASS JP identity and Recent restore, including condition/edition/variant');
  await page.locator('.visiblePreferences [data-value="AUTO"]').click();
  await page.evaluate(()=>makeLink(false));
  const collectionIdentity=await page.evaluate(()=>selectedCardIdentity(document.querySelector('#openBtn').href));
  await page.locator('#collectionAddBtn').click();await page.locator('#collectionEditorSave').click();
  await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)||'[]').length>0,collection);
  const stored=await page.evaluate(k=>JSON.parse(localStorage.getItem(k))[0],collection);
  assert.equal(stored.sourceId,saved.source_id);assert.equal(stored.language,'JP');assert.equal(stored.name,saved.name);assert.equal(stored.number,saved.number);assert.equal(stored.set,saved.set);assert.equal(stored.condition,'EX');assert.equal(stored.edition,'AUTO');assert.equal(stored.variant,saved.variant);assert.equal(stored.cardmarketUrl,collectionIdentity.url);
  console.log('PASS collection stores selected JP card identity with search URL');
  await page.evaluate(async()=>{await applyItem({source_id:'ex15-43',name:'Bagon',number:'43',set:'EX DRAGON FRONTIERS',language:'EN',condition:'NM'},false);await makeLink(false);});
  await page.waitForFunction(()=>document.querySelector('#openBtn').dataset.cmRoute==='EXACT');
  assert.equal(await page.locator('#openBtn span').textContent(),'Open Cardmarket');assert.equal(await page.locator('#openBtn small').textContent(),'Direct naar kaart');assert.equal(await page.locator('#selectedCardRoute').textContent(),'Directe Cardmarket-pagina beschikbaar');
  console.log('PASS known EN exact product route');
  const states=await page.evaluate(()=>{const c=CardmarketUI.classify;return [c('#','pending'),c('#'),c('https://www.cardmarket.com/en/Pokemon/Products/Search?searchString=Snubbull&idProduct=123'),c('https://example.com/en/Pokemon/Products?idProduct=123')];});
  assert.deepEqual(states,['PENDING','UNAVAILABLE','SEARCH','UNAVAILABLE']);
  await page.evaluate(()=>setCardmarketRouteState('pending'));assert.equal(await page.locator('#openBtn').getAttribute('data-cm-route'),'PENDING');assert.equal(await page.locator('#openBtn small').textContent(),'Even geduld');
  await page.evaluate(()=>invalidateCardmarketSelection());assert.equal(await page.locator('#openBtn').getAttribute('data-cm-route'),'UNAVAILABLE');assert.equal(await page.locator('#openBtn small').textContent(),'Kies eerst een kaart');
  assert.deepEqual(errors,[]);console.log('PASS pending/unavailable states, misleading URL rejected, no runtime errors');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
