'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const baseline='bb52604ea331567987d8d79cae94b1995153ad79',out=process.env.UI_SCREENSHOT_DIR||'artifacts/mobile-v153';fs.mkdirSync(out,{recursive:true});
const fixtures=Object.fromEntries(['ex15-43','ex14-4','base2-25'].map(id=>[id,JSON.parse(fs.readFileSync('tests/fixtures/artwork/'+id+'.json'))]));
const recentKey='whatnotai_mobile_recent_v37';
const seed=Array.from({length:12},(_,i)=>({id:'recent-'+i,name:i%2?'Pinsir':'Bagon',number:i%2?'25':'43',set:i%2?'JUNGLE':'EX DRAGON FRONTIERS',lang:'EN',cond:'EX',edition:'AUTO',url:'https://www.cardmarket.com/en/Pokemon/Products?idProduct=273945',exact:true,...(i===0?{source_id:'ex15-43'}:{})}));
seed.forEach(item=>item.quick=[item.name,item.number,item.set].join(' '));
seed[11]={...seed[11],name:'Een uitzonderlijk lange kaartnaam voor de mobiele tekstweergave zonder horizontale overlap'};
let checks=0;const pass=s=>{checks++;console.log('PASS '+s)};
(async()=>{
 require('./helpers/history-protected.cjs')();
 for(const file of ['ui-v137-collection.js','cardmarket-products-v152.js','cards.json','manifest.json'])assert.equal(fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),execFileSync('git',['show',baseline+':'+file],{encoding:'utf8',maxBuffer:20e6}).replace(/\r\n/g,'\n'));pass('Protected routing, pricing, storage/import-export module, mappings, scanner and data unchanged');
 const server=http.createServer((req,res)=>{const file=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';try{res.setHeader('Content-Type',({'js':'text/javascript','css':'text/css','html':'text/html','json':'application/json','svg':'image/svg+xml'})[file.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(path.resolve(file)));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
 for(const width of [320,375,390,430]){
 const ctx=await browser.newContext({viewport:{width,height:844},reducedMotion:'reduce'});await ctx.addInitScript(({key,seed})=>localStorage.setItem(key,JSON.stringify(seed)),{key:recentKey,seed});const page=await ctx.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
 await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='127.0.0.1')return r.continue();if(u.hostname==='api.tcgdex.net'){const id=u.pathname.split('/').pop();if(u.pathname.includes('/cards/')){requests.push(id);return r.fulfill({json:fixtures[id]||{}});}const rows=Object.values(fixtures).filter(x=>x.set.id===id);return r.fulfill({json:{name:rows[0]?.set.name||id,cards:rows.map(x=>({id:x.id,name:x.name,localId:x.localId,image:x.image}))}});}if(u.hostname==='assets.tcgdex.net'){const id=u.pathname.includes('base2')?'base2-25':u.pathname.includes('ex14')?'ex14-4':'ex15-43';return r.fulfill({contentType:'image/webp',body:fs.readFileSync('tests/fixtures/artwork/'+id+'.webp')});}return r.abort();});
 await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#stampedToggle').click();assert.equal(await page.locator('#stampedSetChips').isVisible(),true);
 await page.locator('.visiblePreferences [data-value="EX"]').click();await page.locator('.visiblePreferences [data-value="1ST"]').click();
 const chip=page.locator('[data-stamped-set="EX DRAGON FRONTIERS"]');await chip.scrollIntoViewIfNeeded();await chip.click();assert.equal(await page.locator('#langSelect').inputValue(),'EN');assert.equal(await page.locator('#condSelect').inputValue(),'EX');assert.equal(await page.locator('#editionSelect').inputValue(),'1ST');assert.equal(await chip.getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#stampedSetChips .active').count(),1);assert.ok(await page.locator('.suggestion').count());
 await page.locator('#stampedSetChips button').last().scrollIntoViewIfNeeded();await page.locator('#stampedSetChips button').first().scrollIntoViewIfNeeded();pass(width+'px stamped presets visible, scrollable and preserve preferences');await chip.scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('#toast').hidden);await page.screenshot({path:out+'/presets-'+width+'.png'});
 await page.locator('#quickInput').blur();
 await page.evaluate(async()=>{document.querySelector('#nameInput').value='Bagon';document.querySelector('#numberInput').value='43';document.querySelector('#setSelect').value='EX DRAGON FRONTIERS';selectCardmarketCard({name:'Bagon',number:'43',set:'EX DRAGON FRONTIERS',language:'EN',source_id:'ex15-43'});await makeLink(false);});
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('#actionDock')).opacity==='1');
 for(const count of [1,10,35]){
 await page.evaluate(count=>{const el=document.querySelector('#smartSuggestions');el.hidden=false;el.innerHTML=Array.from({length:count},(_,i)=>'<button class="suggestion" style="height:64px;min-height:64px">Testresultaat '+i+'</button>').join('');document.querySelector('#actionDock').classList.add('ready');document.querySelector('#openBtn').dataset.cmState='ready';el.scrollIntoView({block:'start'});},count);
 await page.waitForTimeout(100);await page.locator('#smartSuggestions').evaluate(el=>el.scrollTop=el.scrollHeight);
 await page.waitForFunction(()=>{const el=document.querySelector('#smartSuggestions'),last=el.lastElementChild.getBoundingClientRect(),box=el.getBoundingClientRect(),dock=document.querySelector('#actionDock').getBoundingClientRect(),nav=document.querySelector('.bottomNav').getBoundingClientRect();return last.top>=box.top-1&&last.bottom<=Math.min(dock.top,nav.top)-8;});
 if(count===1)assert.ok((await page.locator('#smartSuggestions').boundingBox()).height<130);
 await page.waitForFunction(()=>document.querySelector('#toast').hidden);assert.equal(await page.locator('#actionDock').evaluate(el=>getComputedStyle(el).opacity),'1');await page.screenshot({path:out+'/search-'+count+'-'+width+'.png'});
 }pass(width+'px last of 1/10/35 results fully above fixed controls');await page.locator('#selectedCardEdit').scrollIntoViewIfNeeded();await page.waitForTimeout(100);assert.ok(await page.locator('#selectedCardEdit').evaluate(el=>el.getBoundingClientRect().bottom<=document.querySelector('#actionDock').getBoundingClientRect().top-8));await page.screenshot({path:out+'/detail-'+width+'.png'});
 await page.evaluate(({key,seed})=>{localStorage.setItem(key,JSON.stringify(seed));renderSaved();},{key:recentKey,seed});await page.locator('#navRecent').click();await page.locator('#recentList .item').last().scrollIntoViewIfNeeded();await page.waitForTimeout(100);
 assert.ok(await page.locator('#recentList .item').last().evaluate(el=>el.getBoundingClientRect().bottom<=document.querySelector('.bottomNav').getBoundingClientRect().top-8));
 assert.equal(await page.locator('#recentList .useBtn').count(),12);assert.equal(await page.locator('#recentList .delBtn').count(),12);await page.locator('#recentList .item').first().scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('#recentList .recentThumb img')?.naturalWidth>0);
 assert.deepEqual(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).filter(x=>x.id.startsWith('recent-')),recentKey),seed);
 await page.waitForFunction(()=>document.querySelector('#toast').hidden);await page.screenshot({path:out+'/recent-'+width+'.png'});await page.locator('#recentList .item').last().scrollIntoViewIfNeeded();await page.screenshot({path:out+'/recent-last-'+width+'.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass(width+'px recent tiles, images, long names and untouched storage');
 await page.locator('#recentList .delBtn').last().click();assert.equal(await page.locator('#recentList .item').count(),11);
 await page.locator('#recentList .useBtn').first().click();assert.equal(await page.locator('[data-view="search"]').evaluate(el=>el.classList.contains('active')),true);
 await page.locator('#quickClear').click();await page.locator('#homeRecentCards .recentCard').last().scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('#homeRecentCards img')].length===4&&[...document.querySelectorAll('#homeRecentCards img')].every(img=>img.naturalWidth>0));await page.waitForTimeout(100);assert.ok(await page.locator('#homeRecentCards .recentCard').last().evaluate(el=>el.getBoundingClientRect().bottom<=document.querySelector('.bottomNav').getBoundingClientRect().top-8));
 await page.screenshot({path:out+'/previews-'+width+'.png'});pass(width+'px recent actions and last home preview reachable');
 await page.evaluate(({key,item})=>{localStorage.setItem(key,JSON.stringify([item]));renderSaved();},{key:recentKey,item:seed[0]});await page.locator('#navRecent').click();assert.equal(await page.locator('#recentList .useBtn').count(),1);await page.screenshot({path:out+'/recent-single-'+width+'.png'});
 for(const tab of ['navCollection','navSettings']){await page.locator('#'+tab).click();await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await page.waitForTimeout(100);const bounds=await page.locator('.tabView.active').evaluate(el=>({bottom:el.getBoundingClientRect().bottom,nav:document.querySelector('.bottomNav').getBoundingClientRect().top}));assert.ok(bounds.bottom<=bounds.nav-8);}
 pass(width+'px one recent item and page-end clearance on Collection/More');
 if(width===375){
 const before=requests.length;
 await page.evaluate(()=>{const items=[{name:'Bagon',source_id:'ex15-43'},{name:'Pinsir',set:'JUNGLE',number:'25',lang:'EN'},{name:'Bagon',set:'EX DRAGON FRONTIERS',number:'43',image:'not a URL'},{name:'Unknown',source_id:'none-1',language:'EN'}];for(const [i,item]of items.entries()){const t=document.createElement('div');t.id='image-test-'+i;t.style.minHeight='80px';document.body.append(t);window.CardArtwork.mount(item,t);t.scrollIntoView();}});
 for(let i=0;i<4;i++){await page.locator('#image-test-'+i).scrollIntoViewIfNeeded();if(i<3)await page.waitForFunction(i=>document.querySelector('#image-test-'+i+' img')?.naturalWidth>0,i);else await page.locator('#image-test-3.artUnavailable').waitFor();}
 await page.evaluate(async()=>{for(let i=0;i<5;i++)await window.CardArtwork.lookup({name:'Unknown',source_id:'none-1',language:'EN'});});assert.ok(requests.filter(x=>x==='none-1').length<=1);pass('Source ID, legacy Pinsir, invalid URL recovery and cached genuine missing image');
 await page.locator('#navSearch').click();await page.locator('#quickInput').focus();await page.setViewportSize({width,height:480});await page.locator('#quickInput').fill('Bagon');assert.equal(await page.locator('#quickInput').isVisible(),true);await page.locator('#quickInput').blur();await page.setViewportSize({width,height:844});await page.locator('#quickInput').focus();await page.evaluate(()=>{Object.defineProperty(window.visualViewport,'height',{configurable:true,get:()=>innerHeight-300});window.visualViewport.dispatchEvent(new Event('resize'));});await page.waitForFunction(()=>document.body.classList.contains('mobileKeyboard'));assert.equal(await page.locator('#actionDock').evaluate(el=>getComputedStyle(el).visibility),'hidden');await page.evaluate(()=>{delete window.visualViewport.height;window.visualViewport.dispatchEvent(new Event('resize'));});await page.waitForFunction(()=>!document.body.classList.contains('mobileKeyboard'));pass('Reduced viewport and simulated visualViewport keyboard restore (real iOS still needs device QA)');
 }
 assert.deepEqual(errors,[]);await ctx.close();
 }
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
 console.log(checks+' mobile polish checks passed');
})().catch(e=>{console.error(e);process.exitCode=1});
